
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB27LJKl3w7ZU5sCvznFQxLq07PGG0yTqc',
    appId: '1:851962242218:web:21aefeaed3d832fca21cd3',
    messagingSenderId: '851962242218',
    projectId: 'libreria-app-project',
    authDomain: 'libreria-app-project.firebaseapp.com',
    storageBucket: 'libreria-app-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your Android API key
    appId: 'YOUR_APP_ID', // Replace with your Android App ID
    messagingSenderId: '851962242218',
    projectId: 'libreria-app-project',
    storageBucket: 'libreria-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your iOS API key
    appId: 'YOUR_APP_ID', // Replace with your iOS App ID
    messagingSenderId: '851962242218',
    projectId: 'libreria-app-project',
    storageBucket: 'libreria-app-project.appspot.com',
    iosBundleId: 'com.example.app', // Replace with your iOS Bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your macOS API key
    appId: 'YOUR_APP_ID', // Replace with your macOS App ID
    messagingSenderId: '851962242218',
    projectId: 'libreria-app-project',
    storageBucket: 'libreria-app-project.appspot.com',
    iosBundleId: 'com.example.app', // Replace with your iOS Bundle ID
  );

    static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY', // Replace with your windows API key
    appId: 'YOUR_APP_ID', // Replace with your windows App ID
    messagingSenderId: '851962242218',
    projectId: 'libreria-app-project',
    storageBucket: 'libreria-app-project.appspot.com',
  );

}
